export const WILDCARD = "*" as const;

export const ACTIONS = {
  CREATE: "create",
  READ: "read",
  UPDATE: "update",
  DELETE: "delete",
} as const;

export const MODULES = {
  TENETS: "tenets",
  OPERATORS: "operators",
  PARTNERS: "partners",
  ADMIN_GROUPS: "adminGroups",
  WAITLIST: "waitlist",
  STATS: "stats",
  DASHBOARD: "dashboard",
  USERS: "users",
  ORDERS: "orders",
  ANALYTICS: "analytics",
  BOTTLE_MESSAGES: "bottleMessages",
} as const;

type ModuleKey = (typeof MODULES)[keyof typeof MODULES];
type ActionKey = (typeof ACTIONS)[keyof typeof ACTIONS];

const perm = (m: ModuleKey, a: ActionKey): string => `${m}:${a}`;
const all = (m: ModuleKey): string => `${m}:${WILDCARD}`;

export const PERMISSIONS = {
  TENETS: {
    CREATE: perm(MODULES.TENETS, ACTIONS.CREATE),
    READ: perm(MODULES.TENETS, ACTIONS.READ),
    UPDATE: perm(MODULES.TENETS, ACTIONS.UPDATE),
    DELETE: perm(MODULES.TENETS, ACTIONS.DELETE),
    ALL: all(MODULES.TENETS),
  },
  OPERATORS: {
    CREATE: perm(MODULES.OPERATORS, ACTIONS.CREATE),
    READ: perm(MODULES.OPERATORS, ACTIONS.READ),
    UPDATE: perm(MODULES.OPERATORS, ACTIONS.UPDATE),
    DELETE: perm(MODULES.OPERATORS, ACTIONS.DELETE),
    ALL: all(MODULES.OPERATORS),
  },
  PARTNERS: {
    CREATE: perm(MODULES.PARTNERS, ACTIONS.CREATE),
    READ: perm(MODULES.PARTNERS, ACTIONS.READ),
    UPDATE: perm(MODULES.PARTNERS, ACTIONS.UPDATE),
    DELETE: perm(MODULES.PARTNERS, ACTIONS.DELETE),
    ALL: all(MODULES.PARTNERS),
  },
  ADMIN_GROUPS: {
    CREATE: perm(MODULES.ADMIN_GROUPS, ACTIONS.CREATE),
    READ: perm(MODULES.ADMIN_GROUPS, ACTIONS.READ),
    UPDATE: perm(MODULES.ADMIN_GROUPS, ACTIONS.UPDATE),
    DELETE: perm(MODULES.ADMIN_GROUPS, ACTIONS.DELETE),
    ALL: all(MODULES.ADMIN_GROUPS),
  },
  WAITLIST: {
    CREATE: perm(MODULES.WAITLIST, ACTIONS.CREATE),
    READ: perm(MODULES.WAITLIST, ACTIONS.READ),
    UPDATE: perm(MODULES.WAITLIST, ACTIONS.UPDATE),
    DELETE: perm(MODULES.WAITLIST, ACTIONS.DELETE),
    ALL: all(MODULES.WAITLIST),
  },
  STATS: {
    READ: perm(MODULES.STATS, ACTIONS.READ),
    ALL: all(MODULES.STATS),
  },
  BOTTLE_MESSAGES: {
    CREATE: perm(MODULES.BOTTLE_MESSAGES, ACTIONS.CREATE),
    READ: perm(MODULES.BOTTLE_MESSAGES, ACTIONS.READ),
    UPDATE: perm(MODULES.BOTTLE_MESSAGES, ACTIONS.UPDATE),
    DELETE: perm(MODULES.BOTTLE_MESSAGES, ACTIONS.DELETE),
    ALL: all(MODULES.BOTTLE_MESSAGES),
  },
} as const;
